#!/usr/bin/env bash
# =============================================================================
# provision.sh — One-time Azure infrastructure setup for Trader AI
#
# Run this ONCE to create all Azure resources.
# After it completes, copy the printed values into your .env file.
#
# Prerequisites:
#   - Azure CLI installed: https://aka.ms/install-azure-cli
#   - Logged in: az login
#
# Usage:
#   chmod +x deploy/provision.sh
#   ./deploy/provision.sh
# =============================================================================

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
RESOURCE_GROUP="trader-ai-rg"
LOCATION="eastus"                       # change if you prefer another region
STORAGE_ACCOUNT="traderaistorage$RANDOM"  # must be globally unique, lowercase
CONTAINER_NAME="traderai"
ACR_NAME="traderairegistry$RANDOM"      # Azure Container Registry name
ACI_NAME="trader-ai-engine"             # Azure Container Instance name
ACI_CPU=2
ACI_MEMORY=4                            # GB

echo ""
echo "=========================================="
echo "  Trader AI — Azure Provisioning"
echo "=========================================="
echo "Resource Group : $RESOURCE_GROUP"
echo "Location       : $LOCATION"
echo ""

# ── 1. Resource Group ─────────────────────────────────────────────────────────
echo "[1/5] Creating resource group..."
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output none
echo "      Done."

# ── 2. Storage Account + Blob Container ──────────────────────────────────────
echo "[2/5] Creating storage account..."
az storage account create \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --access-tier Hot \
  --output none

STORAGE_CONN=$(az storage account show-connection-string \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --query connectionString \
  --output tsv)

az storage container create \
  --name "$CONTAINER_NAME" \
  --connection-string "$STORAGE_CONN" \
  --output none
echo "      Done. Storage: $STORAGE_ACCOUNT"

# ── 3. Azure Container Registry ───────────────────────────────────────────────
echo "[3/5] Creating container registry..."
az acr create \
  --name "$ACR_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --sku Basic \
  --admin-enabled true \
  --output none

ACR_LOGIN_SERVER=$(az acr show \
  --name "$ACR_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --query loginServer \
  --output tsv)

ACR_USERNAME=$(az acr credential show \
  --name "$ACR_NAME" \
  --query username \
  --output tsv)

ACR_PASSWORD=$(az acr credential show \
  --name "$ACR_NAME" \
  --query "passwords[0].value" \
  --output tsv)

echo "      Done. Registry: $ACR_LOGIN_SERVER"

# ── 4. Save config to deploy/azure.env ────────────────────────────────────────
echo "[4/5] Writing deploy/azure.env..."
cat > "$(dirname "$0")/azure.env" <<EOF
# Auto-generated by provision.sh — DO NOT COMMIT
RESOURCE_GROUP=$RESOURCE_GROUP
LOCATION=$LOCATION
STORAGE_ACCOUNT=$STORAGE_ACCOUNT
ACR_NAME=$ACR_NAME
ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER
ACR_USERNAME=$ACR_USERNAME
ACR_PASSWORD=$ACR_PASSWORD
ACI_NAME=$ACI_NAME
CONTAINER_NAME=$CONTAINER_NAME
EOF
echo "      Done."

# ── 5. Print .env values ──────────────────────────────────────────────────────
echo ""
echo "=========================================="
echo "  Add these values to your .env file:"
echo "=========================================="
echo ""
echo "AZURE_STORAGE_CONN=$STORAGE_CONN"
echo "CONTAINER_NAME=$CONTAINER_NAME"
echo ""
echo "=========================================="
echo "  Provisioning complete."
echo "  Next step: run ./deploy/deploy.sh"
echo "=========================================="
