"""
reporter.py — Telegram bot controller + Discord/Telegram daily HTML session reports.

Telegram bot commands:
    /status    — Current session state (wins, losses, streak, profit)
    /stop      — Halt signal generation immediately
    /start     — Resume signal generation / start new session
    /report    — Send the current session HTML report now
    /threshold — Show current confidence threshold

Discord integration:
    - Sends HTML-formatted session summary to a Discord webhook URL.

Telegram integration:
    - Sends Markdown/HTML session summary to a Telegram chat.
    - Responds to commands via long-polling.

Both channels send at end of session window (or on demand via /report).
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from typing import Any, Protocol, runtime_checkable

import aiohttp

logger = logging.getLogger(__name__)


# ── Orchestrator protocol ─────────────────────────────────────────────────────


@runtime_checkable
class OrchestratorProtocol(Protocol):
    """Interface the Telegram bot expects from the trading orchestrator."""

    def get_status(self) -> dict[str, Any]:
        """Return current session state and configuration."""
        ...

    def stop(self) -> str:
        """Halt signal generation; return a human-readable confirmation."""
        ...

    def resume(self) -> str:
        """Resume signal generation; return a human-readable confirmation."""
        ...

    def start_session(self) -> str:
        """Start a new session; return a human-readable confirmation."""
        ...


# ── HTML report generator ─────────────────────────────────────────────────────


def build_html_report(session_summary: dict[str, Any], status: dict[str, Any]) -> str:
    """
    Build an HTML session performance report.

    Suitable for Discord embed description (truncated) or Telegram HTML mode.

    Args:
        session_summary: Dict with keys like wins, losses, signals_fired,
            net_profit, target_wins, target_profit, elapsed_minutes,
            is_active, target_reached.
        status: Dict with keys like martingale_streak, confidence_threshold.

    Returns:
        A self-contained HTML string with inline styles.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    wins = session_summary.get("wins", 0)
    losses = session_summary.get("losses", 0)
    fired = session_summary.get("signals_fired", 0)
    net = session_summary.get("net_profit", 0.0)
    target_wins = session_summary.get("target_wins", 10)
    target_profit = session_summary.get("target_profit", 20.0)
    elapsed = session_summary.get("elapsed_minutes", 0)
    streak = status.get("martingale_streak", 0)
    threshold = status.get("confidence_threshold", 0.65)
    active = session_summary.get("is_active", False)
    reached = session_summary.get("target_reached", False)

    win_rate = round(wins / max(wins + losses, 1) * 100, 1)

    if active:
        status_badge = "ACTIVE"
    elif reached:
        status_badge = "TARGET REACHED"
    else:
        status_badge = "CLOSED"

    profit_color = "#00ff88" if net >= 0 else "#ff4444"
    streak_color = "#ff8800" if streak > 0 else "#00ff88"

    html = f"""
<html><body style="font-family:monospace;background:#0d0d0d;color:#e0e0e0;padding:20px;">
<h2 style="color:#00ff88;">Trader AI - Daily Session Report</h2>
<p style="color:#888;">{now}</p>

<table style="width:100%;border-collapse:collapse;">
  <tr><td style="padding:6px;color:#aaa;">Session Status</td>
      <td style="padding:6px;color:#fff;font-weight:bold;">{status_badge}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Elapsed</td>
      <td style="padding:6px;">{elapsed} min</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Signals Fired</td>
      <td style="padding:6px;">{fired}</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#00ff88;">Wins</td>
    <td style="padding:6px;color:#00ff88;font-weight:bold;">{wins} / {target_wins}</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#ff4444;">Losses</td>
    <td style="padding:6px;color:#ff4444;font-weight:bold;">{losses}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Win Rate</td>
      <td style="padding:6px;">{win_rate}%</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#aaa;">Net Profit</td>
    <td style="padding:6px;color:{profit_color};font-weight:bold;">
      ${net:.2f} / ${target_profit:.2f}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Martingale Streak</td>
      <td style="padding:6px;color:{streak_color};">{streak} consecutive losses</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Confidence Threshold</td>
      <td style="padding:6px;">{threshold:.0%}</td></tr>
</table>

<p style="margin-top:16px;color:#555;font-size:11px;">
  Generated by Trader AI - Practice mode only until validated
</p>
</body></html>
"""
    return html.strip()


def build_telegram_message(
    session_summary: dict[str, Any], status: dict[str, Any]
) -> str:
    """
    Build a compact Telegram message in HTML format.

    Uses HTML (not Markdown) to avoid issues with special characters
    inside values.

    Args:
        session_summary: Session stats dict (wins, losses, net_profit, etc.).
        status: Global status dict (martingale_streak, confidence_threshold).

    Returns:
        HTML-formatted string ready for Telegram sendMessage.
    """
    wins = session_summary.get("wins", 0)
    losses = session_summary.get("losses", 0)
    net = session_summary.get("net_profit", 0.0)
    target_wins = session_summary.get("target_wins", 10)
    target_profit = session_summary.get("target_profit", 20.0)
    streak = status.get("martingale_streak", 0)
    threshold = status.get("confidence_threshold", 0.65)
    elapsed = session_summary.get("elapsed_minutes", 0)

    win_rate = round(wins / max(wins + losses, 1) * 100, 1)
    profit_icon = "🟢" if net >= 0 else "🔴"
    streak_icon = "🟠" if streak > 0 else "✅"

    return (
        f"<b>📊 Trader AI Session Report</b>\n"
        f"🕐 Elapsed: <code>{elapsed} min</code>\n\n"
        f"✅ Wins: <code>{wins}/{target_wins}</code>\n"
        f"❌ Losses: <code>{losses}</code>\n"
        f"📈 Win Rate: <code>{win_rate}%</code>\n"
        f"{profit_icon} Net Profit: <code>${net:.2f}</code> / <code>${target_profit:.2f}</code>\n"
        f"{streak_icon} Streak: <code>{streak}</code> consecutive losses\n"
        f"🎯 Threshold: <code>{threshold:.0%}</code>\n"
    )


# ── Discord reporter ───────────────────────────────────────────────────────────


class DiscordReporter:
    """
    Sends session reports and alerts to a Discord webhook.

    Uses a shared aiohttp session for connection reuse.  Call :meth:`close`
    when done to release resources.
    """

    ALERT_COLORS: dict[str, int] = {
        "info": 0x5865F2,
        "warning": 0xFF8800,
        "error": 0xFF4444,
    }

    def __init__(self, webhook_url: str) -> None:
        self._url = webhook_url
        self._session: aiohttp.ClientSession | None = None

    async def _get_session(self) -> aiohttp.ClientSession:
        """Lazily create and return a reusable aiohttp session."""
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(
                timeout=aiohttp.ClientTimeout(total=30)
            )
        return self._session

    async def send_report_async(
        self, session_summary: dict[str, Any], status: dict[str, Any]
    ) -> None:
        """
        Send a rich embed summarising the current trading session.

        Args:
            session_summary: Session stats dict.
            status: Global status dict.
        """
        if not self._url:
            return

        text = build_telegram_message(session_summary, status)
        net = session_summary.get("net_profit", 0)
        payload = {
            "embeds": [
                {
                    "title": "📊 Trader AI — Daily Session Report",
                    "description": text.replace("<b>", "**").replace("</b>", "**"),
                    "color": 0x00FF88 if net >= 0 else 0xFF4444,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "footer": {"text": "Trader AI Signal Engine"},
                }
            ]
        }

        try:
            session = await self._get_session()
            async with session.post(self._url, json=payload) as resp:
                await resp.text()
            logger.info({"event": "discord_report_sent"})
        except Exception as exc:
            logger.warning({"event": "discord_report_failed", "error": str(exc)})

    async def send_alert_async(self, message: str, level: str = "info") -> None:
        """
        Send a short alert embed to Discord.

        Args:
            message: Alert body text.
            level: One of ``"info"``, ``"warning"``, or ``"error"``.
        """
        if not self._url:
            return

        payload = {
            "embeds": [
                {
                    "description": message,
                    "color": self.ALERT_COLORS.get(level, self.ALERT_COLORS["info"]),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            ]
        }

        try:
            session = await self._get_session()
            async with session.post(self._url, json=payload) as resp:
                await resp.text()
        except Exception as exc:
            logger.warning({"event": "discord_alert_failed", "error": str(exc)})

    async def close(self) -> None:
        """Close the underlying aiohttp session."""
        if self._session and not self._session.closed:
            await self._session.close()


# ── Telegram bot ───────────────────────────────────────────────────────────────


class TelegramBot:
    """
    Simple long-polling Telegram bot that exposes trading-orchestrator controls.

    Commands:
        /status    — session status
        /stop      — halt signal generation
        /start     — resume / start new session
        /report    — send report now
        /threshold — show current confidence threshold

    Reuses a single :class:`aiohttp.ClientSession` for all API calls.
    """

    BASE_URL = "https://api.telegram.org/bot{token}/{method}"

    def __init__(
        self,
        token: str,
        chat_id: str,
        orchestrator: OrchestratorProtocol,
        discord_reporter: DiscordReporter | None = None,
    ) -> None:
        """
        Args:
            token: Telegram bot token (from BotFather).
            chat_id: Authorized chat id for commands.
            orchestrator: Object that controls signal generation.
            discord_reporter: Optional Discord reporter for dual-channel output.
        """
        self._token = token
        self._chat_id = str(chat_id)
        self._orchestrator = orchestrator
        self._discord = discord_reporter
        self._offset: int = 0
        self._running: bool = False
        self._session: aiohttp.ClientSession | None = None

    async def _get_session(self) -> aiohttp.ClientSession:
        """Lazily create and return a reusable aiohttp session."""
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(
                timeout=aiohttp.ClientTimeout(total=60)
            )
        return self._session

    # ── low-level helpers ──────────────────────────────────────────────────

    async def _api_async(self, method: str, **kwargs: Any) -> dict[str, Any] | None:
        """
        Call a Telegram Bot API method.

        Args:
            method: API method name (e.g. ``"sendMessage"``).
            **kwargs: Parameters forwarded as JSON body.

        Returns:
            Parsed JSON response dict, or ``None`` on failure.
        """
        url = self.BASE_URL.format(token=self._token, method=method)

        try:
            session = await self._get_session()
            async with session.post(url, json=kwargs) as resp:
                if resp.status == 429:
                    retry_after = 5
                    try:
                        body = await resp.json()
                        retry_after = int(
                            body.get("parameters", {}).get("retry_after", 5)
                        )
                    except Exception:
                        pass
                    logger.warning(
                        {
                            "event": "telegram_rate_limited",
                            "method": method,
                            "retry_after": retry_after,
                        }
                    )
                    await asyncio.sleep(retry_after)
                    return None

                data = await resp.json()
                if not data.get("ok"):
                    logger.warning(
                        {
                            "event": "telegram_api_error",
                            "method": method,
                            "response": data,
                        }
                    )
                return data

        except asyncio.TimeoutError:
            logger.warning({"event": "telegram_timeout", "method": method})
        except aiohttp.ClientError as exc:
            logger.warning(
                {
                    "event": "telegram_client_error",
                    "method": method,
                    "error": str(exc),
                }
            )
        except Exception as exc:
            logger.warning(
                {
                    "event": "telegram_request_failed",
                    "method": method,
                    "error": str(exc),
                    "error_type": type(exc).__name__,
                }
            )
        return None

    # ── public interface ───────────────────────────────────────────────────

    async def send_message(self, text: str, parse_mode: str = "HTML") -> None:
        """
        Send a text message to the configured chat.

        Args:
            text: Message body (HTML by default).
            parse_mode: Telegram parse mode (``"HTML"`` or ``"Markdown"``).
        """
        if not text:
            logger.warning({"event": "send_message_empty_text"})
            return
        await self._api_async(
            "sendMessage",
            chat_id=self._chat_id,
            text=text,
            parse_mode=parse_mode,
        )

    async def send_report(self) -> None:
        """Build and send the current session report to Telegram (and Discord)."""
        status = self._orchestrator.get_status()
        session = status.get("session", {})
        msg = build_telegram_message(session, status)
        await self.send_message(msg)

        if self._discord:
            await self._discord.send_report_async(session, status)

    async def poll_loop(self) -> None:
        """Long-polling loop — run as an ``asyncio.Task``."""
        self._running = True
        logger.info({"event": "telegram_bot_started", "chat_id": self._chat_id})

        while self._running:
            try:
                data = await self._api_async(
                    "getUpdates",
                    offset=self._offset,
                    timeout=30,
                    allowed_updates=["message"],
                )

                if not data or not data.get("ok"):
                    await asyncio.sleep(5)
                    continue

                for update in data.get("result", []):
                    self._offset = update["update_id"] + 1
                    msg = update.get("message", {})

                    if str(msg.get("chat", {}).get("id", "")) != self._chat_id:
                        continue

                    text = msg.get("text", "")
                    if not text.startswith("/"):
                        continue

                    reply = await self._handle_command(text)
                    if reply:
                        await self.send_message(reply)

            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.warning({"event": "telegram_poll_error", "error": str(exc)})
                await asyncio.sleep(10)

    async def stop(self) -> None:
        """Signal the polling loop to exit on the next iteration."""
        self._running = False
        # Close session to unblock any in-flight request
        if self._session and not self._session.closed:
            await self._session.close()
            self._session = None

    # ── command dispatch ───────────────────────────────────────────────────

    async def _handle_command(self, text: str) -> str:
        """
        Parse a slash-command and return a reply string.

        Args:
            text: Raw message text starting with ``/``.

        Returns:
            Human-readable reply to send back.
        """
        cmd = text.strip().split()[0].lower().lstrip("/")

        if cmd == "status":
            status = self._orchestrator.get_status()
            session = status.get("session", {})
            return build_telegram_message(session, status)

        if cmd == "stop":
            result = self._orchestrator.stop()
            return result if result else "Signals halted."

        if cmd in ("start", "resume"):
            # Try resume first (handles session-expired case),
            # fall back to start_session
            try:
                result = self._orchestrator.resume()
            except AttributeError:
                result = self._orchestrator.start_session()
            return result if result else "Session started."

        if cmd == "report":
            await self.send_report()
            return ""

        if cmd == "threshold":
            status = self._orchestrator.get_status()
            t = status.get("confidence_threshold", 0.65)
            streak = status.get("martingale_streak", 0)
            return f"Current threshold: <code>{t:.0%}</code> (streak: {streak} losses)"

        return (
            "Available commands:\n"
            "/status - session overview\n"
            "/stop - halt signals\n"
            "/start - resume / new session\n"
            "/report - send report now\n"
            "/threshold - show confidence gate"
        )


# ── Scheduled report sender ───────────────────────────────────────────────────


async def scheduled_report_loop(bot: TelegramBot) -> None:
    """
    Send a daily session report at 23:58 UTC, Monday-Friday only.

    Sleeps in 60-second ticks and fires once per weekday when the clock
    hits 23:58.

    Args:
        bot: A running :class:`TelegramBot` instance to send through.
    """
    last_sent_date: str = ""

    while True:
        await asyncio.sleep(60)
        try:
            now = datetime.now(timezone.utc)

            if now.weekday() > 4:  # skip weekends
                continue
            if now.hour != 23 or now.minute != 58:
                continue

            today = now.strftime("%Y-%m-%d")
            if today == last_sent_date:
                continue

            last_sent_date = today
            await bot.send_report()
            logger.info({"event": "daily_report_sent", "date": today})

        except Exception as exc:
            logger.warning({"event": "scheduled_report_error", "error": str(exc)})
