"""
reporter.py — Telegram bot controller + Discord/Telegram daily HTML session reports.

Telegram bot commands:
  /status   — Current session state (wins, losses, streak, profit)
  /stop     — Halt signal generation immediately
  /start    — Resume signal generation / start new session
  /report   — Send the current session HTML report now
  /threshold — Show current confidence threshold

Discord integration:
  - Sends HTML-formatted session summary to a Discord webhook URL

Telegram integration:
  - Sends Markdown/HTML session summary to a Telegram chat
  - Responds to commands via long-polling

Both channels send at end of session window (or on demand via /report).
"""

from __future__ import annotations

import asyncio
import logging
import os
from datetime import datetime, timezone
from typing import Any, Callable

import requests

logger = logging.getLogger(__name__)


# ── HTML report generator ─────────────────────────────────────────────────────

def build_html_report(session_summary: dict, status: dict) -> str:
    """
    Build an HTML session performance report.
    Suitable for Discord embed description (truncated) or Telegram HTML mode.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    wins = session_summary.get("wins", 0)
    losses = session_summary.get("losses", 0)
    fired = session_summary.get("signals_fired", 0)
    net = session_summary.get("net_profit", 0.0)
    target_wins = session_summary.get("target_wins", 10)
    target_profit = session_summary.get("target_profit", 20.0)
    elapsed = session_summary.get("elapsed_minutes", 0)
    streak = status.get("martingale_streak", 0)
    threshold = status.get("confidence_threshold", 0.65)
    active = session_summary.get("is_active", False)
    reached = session_summary.get("target_reached", False)

    win_rate = round(wins / max(wins + losses, 1) * 100, 1)
    status_badge = "🟢 ACTIVE" if active else ("✅ TARGET REACHED" if reached else "🔴 CLOSED")

    html = f"""
<html><body style="font-family:monospace;background:#0d0d0d;color:#e0e0e0;padding:20px;">
<h2 style="color:#00ff88;">📊 Trader AI — Daily Session Report</h2>
<p style="color:#888;">{now}</p>

<table style="width:100%;border-collapse:collapse;">
  <tr><td style="padding:6px;color:#aaa;">Session Status</td>
      <td style="padding:6px;color:#fff;font-weight:bold;">{status_badge}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Elapsed</td>
      <td style="padding:6px;">{elapsed} min</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Signals Fired</td>
      <td style="padding:6px;">{fired}</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#00ff88;">Wins</td>
    <td style="padding:6px;color:#00ff88;font-weight:bold;">{wins} / {target_wins}</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#ff4444;">Losses</td>
    <td style="padding:6px;color:#ff4444;font-weight:bold;">{losses}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Win Rate</td>
      <td style="padding:6px;">{win_rate}%</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#aaa;">Net Profit</td>
    <td style="padding:6px;color:{'#00ff88' if net >= 0 else '#ff4444'};font-weight:bold;">
      ${net:.2f} / ${target_profit:.2f}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Martingale Streak</td>
      <td style="padding:6px;color:{'#ff8800' if streak > 0 else '#00ff88'};">{streak} consecutive losses</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Confidence Threshold</td>
      <td style="padding:6px;">{threshold:.0%}</td></tr>
</table>

<p style="margin-top:16px;color:#555;font-size:11px;">
  Generated by Trader AI · Practice mode only until validated
</p>
</body></html>
"""
    return html.strip()


def build_telegram_message(session_summary: dict, status: dict) -> str:
    """Build a compact Telegram message (Markdown)."""
    wins = session_summary.get("wins", 0)
    losses = session_summary.get("losses", 0)
    net = session_summary.get("net_profit", 0.0)
    target_wins = session_summary.get("target_wins", 10)
    target_profit = session_summary.get("target_profit", 20.0)
    streak = status.get("martingale_streak", 0)
    threshold = status.get("confidence_threshold", 0.65)
    elapsed = session_summary.get("elapsed_minutes", 0)
    win_rate = round(wins / max(wins + losses, 1) * 100, 1)
    profit_icon = "🟢" if net >= 0 else "🔴"
    streak_icon = "🟠" if streak > 0 else "✅"

    return (
        f"*📊 Trader AI Session Report*\n"
        f"🕐 Elapsed: {elapsed} min\n\n"
        f"✅ Wins: `{wins}/{target_wins}`\n"
        f"❌ Losses: `{losses}`\n"
        f"📈 Win Rate: `{win_rate}%`\n"
        f"{profit_icon} Net Profit: `${net:.2f}` / `${target_profit:.2f}`\n"
        f"{streak_icon} Streak: `{streak}` consecutive losses\n"
        f"🎯 Threshold: `{threshold:.0%}`\n"
    )


# ── Discord reporter ───────────────────────────────────────────────────────────

class DiscordReporter:
    """Sends session reports to a Discord webhook."""

    def __init__(self, webhook_url: str) -> None:
        self._url = webhook_url

    def send_report(self, session_summary: dict, status: dict) -> None:
        if not self._url:
            return
        text = build_telegram_message(session_summary, status)
        html = build_html_report(session_summary, status)

        # Discord supports embeds; send the text as an embed description
        payload = {
            "embeds": [
                {
                    "title": "📊 Trader AI — Daily Session Report",
                    "description": text.replace("*", "**"),  # Discord uses **bold**
                    "color": 0x00FF88 if session_summary.get("net_profit", 0) >= 0 else 0xFF4444,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "footer": {"text": "Trader AI Signal Engine"},
                }
            ]
        }
        try:
            resp = requests.post(self._url, json=payload, timeout=10)
            resp.raise_for_status()
            logger.info({"event": "discord_report_sent", "status": resp.status_code})
        except Exception as exc:
            logger.warning({"event": "discord_report_failed", "error": str(exc)})

    def send_alert(self, message: str, level: str = "info") -> None:
        """Send a plain-text alert to Discord."""
        if not self._url:
            return
        colors = {"info": 0x5865F2, "warning": 0xFF8800, "error": 0xFF4444}
        payload = {
            "embeds": [
                {
                    "description": message,
                    "color": colors.get(level, 0x5865F2),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            ]
        }
        try:
            requests.post(self._url, json=payload, timeout=10)
        except Exception as exc:
            logger.warning({"event": "discord_alert_failed", "error": str(exc)})


# ── Telegram bot ───────────────────────────────────────────────────────────────

class TelegramBot:
    """
    Simple long-polling Telegram bot.

    Commands:
      /status   — session status
      /stop     — halt signal generation
      /start    — resume / start new session
      /report   — send report now
      /threshold — show current confidence threshold
    """

    BASE_URL = "https://api.telegram.org/bot{token}/{method}"

    def __init__(
        self,
        token: str,
        chat_id: str,
        orchestrator,
        discord_reporter: DiscordReporter | None = None,
    ) -> None:
        self._token = token
        self._chat_id = chat_id
        self._orchestrator = orchestrator
        self._discord = discord_reporter
        self._offset: int = 0
        self._running = False

    def _api(self, method: str, **kwargs) -> dict | None:
        url = self.BASE_URL.format(token=self._token, method=method)
        try:
            resp = requests.post(url, json=kwargs, timeout=15)
            data = resp.json()
            if not data.get("ok"):
                logger.warning({"event": "telegram_api_error", "method": method, "response": data})
            return data
        except Exception as exc:
            logger.warning({"event": "telegram_request_failed", "method": method, "error": str(exc)})
            return None

    def send_message(self, text: str, parse_mode: str = "Markdown") -> None:
        self._api("sendMessage", chat_id=self._chat_id, text=text, parse_mode=parse_mode)

    def send_report(self) -> None:
        status = self._orchestrator.get_status()
        session = status.get("session", {})
        msg = build_telegram_message(session, status)
        self.send_message(msg)
        if self._discord:
            self._discord.send_report(session, status)

    def _handle_command(self, text: str) -> str:
        cmd = text.strip().split()[0].lower().lstrip("/")

        if cmd == "status":
            status = self._orchestrator.get_status()
            session = status.get("session", {})
            return build_telegram_message(session, status)

        elif cmd == "stop":
            return self._orchestrator.stop()

        elif cmd in ("start", "resume"):
            return self._orchestrator.start_session()

        elif cmd == "report":
            self.send_report()
            return "Report sent."

        elif cmd == "threshold":
            status = self._orchestrator.get_status()
            t = status.get("confidence_threshold", 0.65)
            streak = status.get("martingale_streak", 0)
            return f"Current threshold: `{t:.0%}` (streak: {streak} losses)"

        else:
            return (
                "Available commands:\n"
                "/status — session overview\n"
                "/stop — halt signals\n"
                "/start — resume / new session\n"
                "/report — send report now\n"
                "/threshold — show confidence gate"
            )

    async def poll_loop(self) -> None:
        """Long-polling loop — runs as an asyncio task."""
        self._running = True
        logger.info({"event": "telegram_bot_started", "chat_id": self._chat_id})
        while self._running:
            try:
                data = self._api(
                    "getUpdates",
                    offset=self._offset,
                    timeout=30,
                    allowed_updates=["message"],
                )
                if not data or not data.get("ok"):
                    await asyncio.sleep(5)
                    continue

                for update in data.get("result", []):
                    self._offset = update["update_id"] + 1
                    msg = update.get("message", {})
                    # Only process messages from our chat_id
                    if str(msg.get("chat", {}).get("id", "")) != str(self._chat_id):
                        continue
                    text = msg.get("text", "")
                    if not text.startswith("/"):
                        continue
                    reply = self._handle_command(text)
                    self.send_message(reply)

            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.warning({"event": "telegram_poll_error", "error": str(exc)})
                await asyncio.sleep(10)

    def stop(self) -> None:
        self._running = False


# ── Scheduled report sender ───────────────────────────────────────────────────

async def scheduled_report_loop(
    bot: TelegramBot,
    _orchestrator: Any = None,
    _interval_minutes: int = 60,
) -> None:
    """
    Sends a daily session report at 23:58 UTC, Monday–Friday only.
    Sleeps in 30-second ticks and fires when the clock hits 23:58.
    """
    last_sent_date: str = ""
    while True:
        await asyncio.sleep(30)
        try:
            now = datetime.now(timezone.utc)
            # 0=Monday … 4=Friday
            if now.weekday() > 4:
                continue
            if now.hour != 23 or now.minute != 58:
                continue
            today = now.strftime("%Y-%m-%d")
            if today == last_sent_date:
                continue  # already sent today
            last_sent_date = today
            bot.send_report()
            logger.info({"event": "daily_report_sent", "date": today})
        except Exception as exc:
            logger.warning({"event": "scheduled_report_error", "error": str(exc)})
