"""
reporter.py — Telegram bot controller + Discord/Telegram daily HTML session reports.

Telegram bot commands:
    /status    — Current session state (wins, losses, streak, profit)
    /stop      — Halt signal generation immediately
    /start     — Resume signal generation / start new session
    /report    — Send the current session HTML report now
    /threshold — Show current confidence threshold

Discord integration:
    - Sends HTML-formatted session summary to a Discord webhook URL.

Telegram integration:
    - Sends Markdown/HTML session summary to a Telegram chat.
    - Responds to commands via long-polling.

Both channels send at end of session window (or on demand via /report).
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from typing import Any, Protocol, runtime_checkable

import aiohttp

logger = logging.getLogger(__name__)


# ── Orchestrator protocol ─────────────────────────────────────────────────────


@runtime_checkable
class OrchestratorProtocol(Protocol):
    """Interface the Telegram bot expects from the trading orchestrator."""

    def get_status(self) -> dict[str, Any]:
        """Return current session state and configuration."""
        ...

    def stop(self) -> str:
        """Halt signal generation; return a human-readable confirmation."""
        ...

    def resume(self) -> str:
        """Resume signal generation; return a human-readable confirmation."""
        ...

    def start_session(self) -> str:
        """Start a new session; return a human-readable confirmation."""
        ...


# ── HTML report generator ─────────────────────────────────────────────────────


def build_html_report(
    session_summary: dict[str, Any], status: dict[str, Any]
) -> str:
    """
    Build an HTML session performance report.

    Suitable for Discord embed description (truncated) or Telegram HTML mode.

    Args:
        session_summary: Dict with keys like wins, losses, signals_fired,
            net_profit, target_wins, target_profit, elapsed_minutes,
            is_active, target_reached.
        status: Dict with keys like martingale_streak, confidence_threshold.

    Returns:
        A self-contained HTML string with inline styles.
    """
    now: str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    wins: int = session_summary.get("wins", 0)
    losses: int = session_summary.get("losses", 0)
    fired: int = session_summary.get("signals_fired", 0)
    net: float = session_summary.get("net_profit", 0.0)
    target_wins: int = session_summary.get("target_wins", 10)
    target_profit: float = session_summary.get("target_profit", 20.0)
    elapsed: int = session_summary.get("elapsed_minutes", 0)
    streak: int = status.get("martingale_streak", 0)
    threshold: float = status.get("confidence_threshold", 0.65)
    active: bool = session_summary.get("is_active", False)
    reached: bool = session_summary.get("target_reached", False)

    win_rate: float = round(wins / max(wins + losses, 1) * 100, 1)

    if active:
        status_badge: str = "ACTIVE"
    elif reached:
        status_badge = "TARGET REACHED"
    else:
        status_badge = "CLOSED"

    profit_color: str = "#00ff88" if net >= 0 else "#ff4444"
    streak_color: str = "#ff8800" if streak > 0 else "#00ff88"

    html: str = f"""
<html><body style="font-family:monospace;background:#0d0d0d;color:#e0e0e0;padding:20px;">
<h2 style="color:#00ff88;">Trader AI - Daily Session Report</h2>
<p style="color:#888;">{now}</p>

<table style="width:100%;border-collapse:collapse;">
  <tr><td style="padding:6px;color:#aaa;">Session Status</td>
      <td style="padding:6px;color:#fff;font-weight:bold;">{status_badge}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Elapsed</td>
      <td style="padding:6px;">{elapsed} min</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Signals Fired</td>
      <td style="padding:6px;">{fired}</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#00ff88;">Wins</td>
    <td style="padding:6px;color:#00ff88;font-weight:bold;">{wins} / {target_wins}</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#ff4444;">Losses</td>
    <td style="padding:6px;color:#ff4444;font-weight:bold;">{losses}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Win Rate</td>
      <td style="padding:6px;">{win_rate}%</td></tr>
  <tr style="background:#1a1a1a;">
    <td style="padding:6px;color:#aaa;">Net Profit</td>
    <td style="padding:6px;color:{profit_color};font-weight:bold;">
      ${net:.2f} / ${target_profit:.2f}</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Martingale Streak</td>
      <td style="padding:6px;color:{streak_color};">{streak} consecutive losses</td></tr>
  <tr><td style="padding:6px;color:#aaa;">Confidence Threshold</td>
      <td style="padding:6px;">{threshold:.0%}</td></tr>
</table>

<p style="margin-top:16px;color:#555;font-size:11px;">
  Generated by Trader AI - Practice mode only until validated
</p>
</body></html>
"""
    return html.strip()


def build_telegram_message(
    session_summary: dict[str, Any], status: dict[str, Any]
) -> str:
    """
    Build a compact Telegram message in HTML format.

    Uses HTML (not Markdown) to avoid issues with special characters
    inside values.

    Args:
        session_summary: Session stats dict (wins, losses, net_profit, etc.).
        status: Global status dict (martingale_streak, confidence_threshold).

    Returns:
        HTML-formatted string ready for Telegram sendMessage.
    """
    wins: int = session_summary.get("wins", 0)
    losses: int = session_summary.get("losses", 0)
    net: float = session_summary.get("net_profit", 0.0)
    target_wins: int = session_summary.get("target_wins", 10)
    target_profit: float = session_summary.get("target_profit", 20.0)
    streak: int = status.get("martingale_streak", 0)
    threshold: float = status.get("confidence_threshold", 0.65)
    elapsed: int = session_summary.get("elapsed_minutes", 0)

    win_rate: float = round(wins / max(wins + losses, 1) * 100, 1)
    profit_icon: str = "🟢" if net >= 0 else "🔴"
    streak_icon: str = "🟠" if streak > 0 else "✅"

    return (
        f"<b>📊 Trader AI Session Report</b>\n"
        f"🕐 Elapsed: <code>{elapsed} min</code>\n\n"
        f"✅ Wins: <code>{wins}/{target_wins}</code>\n"
        f"❌ Losses: <code>{losses}</code>\n"
        f"📈 Win Rate: <code>{win_rate}%</code>\n"
        f"{profit_icon} Net Profit: <code>${net:.2f}</code> / "
        f"<code>${target_profit:.2f}</code>\n"
        f"{streak_icon} Streak: <code>{streak}</code> consecutive losses\n"
        f"🎯 Threshold: <code>{threshold:.0%}</code>\n"
    )


def build_discord_message(
    session_summary: dict[str, Any], status: dict[str, Any]
) -> str:
    """
    Build a plain-text session summary for Discord embeds.

    Discord embed descriptions support markdown, not HTML.  This function
    produces a clean string with no HTML tags.

    Args:
        session_summary: Session stats dict.
        status: Global status dict.

    Returns:
        Plain-text string safe for Discord embed description.
    """
    wins: int = session_summary.get("wins", 0)
    losses: int = session_summary.get("losses", 0)
    net: float = session_summary.get("net_profit", 0.0)
    target_wins: int = session_summary.get("target_wins", 10)
    target_profit: float = session_summary.get("target_profit", 20.0)
    streak: int = status.get("martingale_streak", 0)
    threshold: float = status.get("confidence_threshold", 0.65)
    elapsed: int = session_summary.get("elapsed_minutes", 0)

    win_rate: float = round(wins / max(wins + losses, 1) * 100, 1)
    profit_icon: str = "🟢" if net >= 0 else "🔴"
    streak_icon: str = "🟠" if streak > 0 else "✅"

    return (
        f"**📊 Trader AI Session Report**\n"
        f"🕐 Elapsed: `{elapsed} min`\n\n"
        f"✅ Wins: `{wins}/{target_wins}`\n"
        f"❌ Losses: `{losses}`\n"
        f"📈 Win Rate: `{win_rate}%`\n"
        f"{profit_icon} Net Profit: `${net:.2f}` / `${target_profit:.2f}`\n"
        f"{streak_icon} Streak: `{streak}` consecutive losses\n"
        f"🎯 Threshold: `{threshold:.0%}`\n"
    )


# ── Discord reporter ───────────────────────────────────────────────────────────


class DiscordReporter:
    """
    Sends session reports and alerts to a Discord webhook.

    Uses a shared aiohttp session for connection reuse.  Call :meth:`close`
    when done to release resources.
    """

    ALERT_COLORS: dict[str, int] = {
        "info": 0x5865F2,
        "warning": 0xFF8800,
        "error": 0xFF4444,
    }

    def __init__(self, webhook_url: str) -> None:
        self._url: str = webhook_url
        self._session: aiohttp.ClientSession | None = None

    async def _get_session(self) -> aiohttp.ClientSession:
        """
        Lazily create and return a reusable aiohttp session.

        Returns:
            An open :class:`aiohttp.ClientSession`.
        """
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(
                timeout=aiohttp.ClientTimeout(total=30)
            )
        return self._session

    async def send_report_async(
        self, session_summary: dict[str, Any], status: dict[str, Any]
    ) -> None:
        """
        Send a rich embed summarising the current trading session.

        Uses :func:`build_discord_message` (plain-text, no HTML) so the
        embed description renders correctly in Discord.

        Args:
            session_summary: Session stats dict.
            status: Global status dict.
        """
        if not self._url:
            return

        text: str = build_discord_message(session_summary, status)
        net: float = session_summary.get("net_profit", 0)
        payload: dict[str, Any] = {
            "embeds": [
                {
                    "title": "📊 Trader AI — Daily Session Report",
                    "description": text,
                    "color": 0x00FF88 if net >= 0 else 0xFF4444,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "footer": {"text": "Trader AI Signal Engine"},
                }
            ]
        }

        try:
            session = await self._get_session()
            async with session.post(self._url, json=payload) as resp:
                await resp.text()
            logger.info({"event": "discord_report_sent"})
        except Exception as exc:
            logger.warning(
                {"event": "discord_report_failed", "error": str(exc)}
            )

    async def send_alert_async(
        self, message: str, level: str = "info"
    ) -> None:
        """
        Send a short alert embed to Discord.

        Args:
            message: Alert body text (plain text, no HTML).
            level: One of ``"info"``, ``"warning"``, or ``"error"``.
        """
        if not self._url:
            return

        payload: dict[str, Any] = {
            "embeds": [
                {
                    "description": message,
                    "color": self.ALERT_COLORS.get(
                        level, self.ALERT_COLORS["info"]
                    ),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            ]
        }

        try:
            session = await self._get_session()
            async with session.post(self._url, json=payload) as resp:
                await resp.text()
        except Exception as exc:
            logger.warning(
                {"event": "discord_alert_failed", "error": str(exc)}
            )

    async def close(self) -> None:
        """Close the underlying aiohttp session."""
        if self._session and not self._session.closed:
            await self._session.close()


# ── Telegram bot ───────────────────────────────────────────────────────────────


class TelegramBot:
    """
    Simple long-polling Telegram bot that exposes trading-orchestrator controls.

    Commands:
        /status    — session status
        /stop      — halt signal generation
        /start     — resume / start new session
        /report    — send report now
        /threshold — show current confidence threshold

    Reuses a single :class:`aiohttp.ClientSession` for all API calls.
    """

    BASE_URL: str = "https://api.telegram.org/bot{token}/{method}"
    MAX_RETRIES: int = 3
    RETRY_DELAY: float = 2.0

    def __init__(
        self,
        token: str,
        chat_id: str,
        orchestrator: OrchestratorProtocol,
        discord_reporter: DiscordReporter | None = None,
    ) -> None:
        """
        Args:
            token: Telegram bot token (from BotFather).
            chat_id: Authorized chat id for commands.
            orchestrator: Object that controls signal generation.
            discord_reporter: Optional Discord reporter for dual-channel output.
        """
        self._token: str = token
        self._chat_id: str = str(chat_id)
        self._orchestrator: OrchestratorProtocol = orchestrator
        self._discord: DiscordReporter | None = discord_reporter
        self._offset: int = 0
        self._running: bool = False
        self._session: aiohttp.ClientSession | None = None

    async def _get_session(self) -> aiohttp.ClientSession:
        """
        Lazily create and return a reusable aiohttp session.

        Returns:
            An open :class:`aiohttp.ClientSession` with 60s timeout.
        """
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(
                timeout=aiohttp.ClientTimeout(total=60)
            )
        return self._session

    # ── Low-level helpers ──────────────────────────────────────────────────

    async def _api_async(
        self,
        method: str,
        max_retries: int | None = None,
        **kwargs: Any,
    ) -> dict[str, Any] | None:
        """
        Call a Telegram Bot API method with retry on rate limit.

        On HTTP 429, sleeps for the ``retry_after`` duration and retries
        up to *max_retries* times before giving up.

        Args:
            method: API method name (e.g. ``"sendMessage"``).
            max_retries: Override for retry count (default :attr:`MAX_RETRIES`).
            **kwargs: Parameters forwarded as JSON body.

        Returns:
            Parsed JSON response dict, or ``None`` on permanent failure.
        """
        if max_retries is None:
            max_retries = self.MAX_RETRIES

        url: str = self.BASE_URL.format(token=self._token, method=method)

        for attempt in range(1, max_retries + 1):
            try:
                session = await self._get_session()
                async with session.post(url, json=kwargs) as resp:
                    if resp.status == 429:
                        retry_after: int = 5
                        try:
                            body: dict[str, Any] = await resp.json()
                            retry_after = int(
                                body.get("parameters", {}).get(
                                    "retry_after", 5
                                )
                            )
                        except Exception:
                            pass
                        logger.warning(
                            {
                                "event": "telegram_rate_limited",
                                "method": method,
                                "attempt": attempt,
                                "retry_after": retry_after,
                            }
                        )
                        if attempt < max_retries:
                            await asyncio.sleep(retry_after)
                            continue
                        return None

                    data: dict[str, Any] = await resp.json()
                    if not data.get("ok"):
                        logger.warning(
                            {
                                "event": "telegram_api_error",
                                "method": method,
                                "response": data,
                            }
                        )
                    return data

            except asyncio.TimeoutError:
                logger.warning(
                    {
                        "event": "telegram_timeout",
                        "method": method,
                        "attempt": attempt,
                    }
                )
            except aiohttp.ClientError as exc:
                logger.warning(
                    {
                        "event": "telegram_client_error",
                        "method": method,
                        "attempt": attempt,
                        "error": str(exc),
                    }
                )
            except Exception as exc:
                logger.warning(
                    {
                        "event": "telegram_request_failed",
                        "method": method,
                        "attempt": attempt,
                        "error": str(exc),
                        "error_type": type(exc).__name__,
                    }
                )

            if attempt < max_retries:
                await asyncio.sleep(self.RETRY_DELAY)

        return None

    # ── Public interface ───────────────────────────────────────────────────

    async def send_message(
        self, text: str, parse_mode: str = "HTML"
    ) -> None:
        """
        Send a text message to the configured chat.

        Args:
            text: Message body (HTML by default).
            parse_mode: Telegram parse mode (``"HTML"`` or ``"Markdown"``).
        """
        if not text:
            logger.warning({"event": "send_message_empty_text"})
            return
        await self._api_async(
            "sendMessage",
            chat_id=self._chat_id,
            text=text,
            parse_mode=parse_mode,
        )

    async def send_report(self) -> None:
        """
        Build and send the current session report to Telegram (and Discord).

        Uses :func:`build_telegram_message` for Telegram (HTML) and
        :func:`build_discord_message` for Discord (plain text).
        """
        status: dict[str, Any] = self._orchestrator.get_status()
        session: dict[str, Any] = status.get("session", {})
        msg: str = build_telegram_message(session, status)
        await self.send_message(msg)

        if self._discord:
            await self._discord.send_report_async(session, status)

    async def poll_loop(self) -> None:
        """
        Long-polling loop — run as an ``asyncio.Task``.

        Continuously fetches updates from Telegram and dispatches
        commands from the authorized chat.
        """
        self._running = True
        logger.info(
            {"event": "telegram_bot_started", "chat_id": self._chat_id}
        )

        while self._running:
            try:
                data: dict[str, Any] | None = await self._api_async(
                    "getUpdates",
                    offset=self._offset,
                    timeout=30,
                    allowed_updates=["message"],
                )

                if not data or not data.get("ok"):
                    await asyncio.sleep(5)
                    continue

                for update in data.get("result", []):
                    self._offset = update["update_id"] + 1
                    msg: dict[str, Any] = update.get("message", {})

                    if (
                        str(msg.get("chat", {}).get("id", ""))
                        != self._chat_id
                    ):
                        continue

                    text: str = msg.get("text", "")
                    if not text.startswith("/"):
                        continue

                    reply: str = await self._handle_command(text)
                    if reply:
                        await self.send_message(reply)

            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.warning(
                    {"event": "telegram_poll_error", "error": str(exc)}
                )
                await asyncio.sleep(10)

    async def stop(self) -> None:
        """
        Signal the polling loop to exit on the next iteration.

        Closes the aiohttp session to unblock any in-flight long-poll.
        """
        self._running = False
        if self._session and not self._session.closed:
            await self._session.close()
            self._session = None

    # ── Command dispatch ───────────────────────────────────────────────────

    async def _handle_command(self, text: str) -> str:
        """
        Parse a slash-command and return a reply string.

        Args:
            text: Raw message text starting with ``/``.

        Returns:
            Human-readable reply to send back, or empty string for
            commands that handle their own sending (e.g. ``/report``).
        """
        cmd: str = text.strip().split()[0].lower().lstrip("/")

        if cmd == "status":
            status: dict[str, Any] = self._orchestrator.get_status()
            session: dict[str, Any] = status.get("session", {})
            return build_telegram_message(session, status)

        if cmd == "stop":
            result: str = self._orchestrator.stop()
            return result if result else "Signals halted."

        if cmd in ("start", "resume"):
            try:
                result = self._orchestrator.resume()
            except AttributeError:
                result = self._orchestrator.start_session()
            return result if result else "Session started."

        if cmd == "report":
            await self.send_report()
            return ""

        if cmd == "threshold":
            status = self._orchestrator.get_status()
            t: float = status.get("confidence_threshold", 0.65)
            streak: int = status.get("martingale_streak", 0)
            return (
                f"Current threshold: <code>{t:.0%}</code> "
                f"(streak: {streak} losses)"
            )

        return (
            "Available commands:\n"
            "/status - session overview\n"
            "/stop - halt signals\n"
            "/start - resume / new session\n"
            "/report - send report now\n"
            "/threshold - show confidence gate"
        )


# ── Scheduled report sender ───────────────────────────────────────────────────


async def scheduled_report_loop(bot: TelegramBot) -> None:
    """
    Send a daily session report at 23:58 UTC, Monday-Friday only.

    Sleeps in 60-second ticks and fires once per weekday when the clock
    hits 23:58.

    Args:
        bot: A running :class:`TelegramBot` instance to send through.
    """
    last_sent_date: str = ""

    while True:
        await asyncio.sleep(60)
        try:
            now: datetime = datetime.now(timezone.utc)

            if now.weekday() > 4:  # skip weekends
                continue
            if now.hour != 23 or now.minute != 58:
                continue

            today: str = now.strftime("%Y-%m-%d")
            if today == last_sent_date:
                continue

            last_sent_date = today
            await bot.send_report()
            logger.info({"event": "daily_report_sent", "date": today})

        except Exception as exc:
            logger.warning(
                {"event": "scheduled_report_error", "error": str(exc)}
            )
